project:
  type: website
  output-dir: docs

website:
  title: "ENVS-193DS_HW-5"
  navbar:
    left:
      - href: 193DS-HW_05.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



